spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      # 连接池配置
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      filters: stat,wall,logback
      poolPreparedStatements: true  #打开PSCache
      maxOpenPreparedStatements: 20   #指定每个连接的PSCache大小
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password:
    #    lettuce:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  #mybatis:
  #  mapper-locations: classpath:mapping/*Mapper.xml
  #  type-aliases-package: com.example.demo.model

  ##################
  #  MQTT 配置
  ##################
  # 用户名
#  mqtt.username=admin
  # 密码
#  mqtt.password=password
  # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
#  mqtt.url=tcp://127.0.0.1:61613
  ##################
  #  MQTT 生产者
  ##################
  # 连接服务器默认客户端ID
#  mqtt.producer.clientId=mqttProducer
  # 默认的推送主题，实际可在调用接口时指定
#  mqtt.producer.defaultTopic=topic1
  ##################
  #  MQTT 消费者
  ##################
  # 连接服务器默认客户端ID
#  mqtt.consumer.clientId=mqttConsumer
  # 默认的接收主题，可以订阅多个Topic，逗号分隔
#  mqtt.consumer.defaultTopic=topic1
  mqtt:
    username: admin
    password: 123456
#    MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:616
    url: tcp://127.0.0.1:1883,tcp://127.0.0.1:11883
    producer:
      clientId: mqttProducer
      defaultTopic: topic1,topic2
    consumer:
      clientId: ${random.value}
      defaultTopic: topic1,topic2

