server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: message/messages
  #编码格式
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

    # 最大支持文件大小 即单个文件大小
#    spring.http.multipart.max-file-size=1Mb
    # 最大支持请求大小 即一次性上传的总文件大小
#    spring.http.multipart.max-request-size=10Mb

#  spring.http.encoding.force=true
#  spring.http.encoding.charset=UTF-8
#  spring.http.encoding.enabled=true
#  server.tomcat.uri-encoding=UTF-8

file:
  upload:
    dir: d://item_files
      #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880